name: Build Flutter APK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download and set up Flutter
      - name: Set up Flutter
        run: |
          # Download Flutter SDK
          curl -o flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.6-stable.tar.xz
          tar xf flutter.tar.xz
          export PATH="$PWD/flutter/bin:$PATH"

          # Ensure Flutter commands are available
          echo $PATH
          which flutter
          flutter --version
          dart --version

      # Step 3: Disable Flutter telemetry (optional)
      - name: Disable Flutter telemetry
        run: |
          export PATH="$PWD/flutter/bin:$PATH"
          flutter config --no-analytics

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          export PATH="$PWD/flutter/bin:$PATH"
          flutter pub get

      # Step 5: Build APK
      - name: Build APK
        run: |
          export PATH="$PWD/flutter/bin:$PATH"
          flutter build apk --debug

      # Step 6: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
